### PR TITLE
Update newdemo.txt

### PR DESCRIPTION
**Pull request by Nan-StartUp**
再次测试

### CODE REVIEW

**Comment by Nan-StartUp** [comment]
"demo2"

**Comment by StartUp-bigdata** [comment]
"demo2 ddd'

**Review by StartUp-bigdata — COMMENTED** [review]
"vhf

**Comment by Nan-StartUp** [comment]
年纪

**Review by Nan-StartUp — COMMENTED** [review]
"帆帆帆帆"

**Review by Nan-StartUp — COMMENTED** [review]
"""灌灌灌灌

**Pull request closed without merging**
